#!/bin/sh

sxhkd &
nitrogen --restore &
xsetroot -cursor_name left_ptr &
picom -f &
xset s 3600 3600 &

bspc monitor -d www dev media chat other

bspc config border_width          2
bspc config focused_border_color  \#161012
bspc config active_border_color   \#fefefe
bspc config normal_border_color   \#161012
bspc config window_gap            20

bspc config split_ratio           0.52
bspc config borderless_monocle    false
bspc config gapless_monocle       false

# www desktop
bspc rule --add firefox           desktop='www' state=tiled

# dev desktop
bspc rule --add Code              desktop='dev' state=tiled

# media desktop
bspc rule --add Spotify           desktop='media' state=pseudo_tiled

# chat desktop

# other desktop

# just states
bspc rule --add Alacritty         state=pseudo_tiled
bspc rule --add Ulauncher         state=floating  border=off
