#!/bin/sh

xrandr -s 1920x1080
sxhkd &
ulauncher &
nitrogen --restore &
xsetroot -cursor_name left_ptr &
picom -f &
xset s 3600 3600 &
sh ~/.config/polybar/launch.sh & 
nm-applet &

bspc monitor -d www dev media chat other

bspc config border_width          2
bspc config focused_border_color  \#161012
bspc config active_border_color   \#fefefe
bspc config normal_border_color   \#161012
bspc config window_gap            0
bspc config gapless_monocle       true
bspc config borderless_monocle    true


bspc config split_ratio           0.52

# www desktop
bspc rule --add Firefox           desktop='www' state=tiled

# dev desktop
bspc rule --add Code              desktop='dev' state=tiled

# media desktop
bspc rule --add Spotify           desktop='media' state=pseudo_tiled

# chat desktop

# other desktop

# just states
bspc rule --add Alacritty         state=pseudo_tiled
bspc rule --add Ulauncher         state=floating  border=off


